# Generated by Django 3.0.7 on 2020-06-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='message_id',
            field=models.IntegerField(null=True),
        ),
    ]
