# Generated by Django 3.0.7 on 2020-06-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='message_id',
            new_name='manager_message_id',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user_message_id',
            field=models.IntegerField(null=True),
        ),
    ]
