# Generated by Django 3.0.7 on 2020-06-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200626_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='name', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
