# Generated by Django 3.0.7 on 2020-07-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200629_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo_url',
            field=models.URLField(null=True),
        ),
    ]
