# Generated by Django 3.0.7 on 2020-07-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_item_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='item',
            name='photo_file_unique_id',
            field=models.TextField(null=True),
        ),
    ]
