# Generated by Django 3.0.7 on 2020-07-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200702_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
