# Generated by Django 3.0.8 on 2020-07-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_shippingpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
    ]
